import "./globals.css";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { Stack } from "@mui/material";
import { NotistackProvider } from "./components/SnackbarProviderClient";
import LeftMenu from "./components/LeftMenu";

export const metadata = {
  title: "LLM RCTs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NotistackProvider>
        <body>
          <Stack direction='row' width='100%'>
            <LeftMenu />
            {children}
          </Stack>
        </body>
      </NotistackProvider>
    </html>
  );
}
